#!/bin/sh
rsync -av ./ mbbggnmy@70.40.220.120:~/public_html/test --include=public/build --include=public/.htaccess --exclude-from=.gitignore --exclude=".*"  --exclude=.env
#ssh genesjz7@genesistech-dz.com 'cd ~/public_html/foodshack && php bin/console cache:clear'